### ISSUE TITLE
Common code format,

### ISSUE THREAD

**Issue by mdanter** [ge0ffrey/optaconf#12]
I've been using this: https://github.com/ocpsoft/common/blob/master/ocpsoft-eclipse-code-format.xml to format the code I've been creating for this project. I would like to conform to the style you're adhering to. Could you please provide this info/formatter so that you don't have to reformat my code if I auto format it with the eclipse code formatter?

**Comment by ge0ffrey** [comment]
I use the same one as upstream optaplanner, drools & jbpm:
  https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/tree/master/ide-configuration
That one is compatible with Sun/Oracle coding conventions and JBoss coding conventions (well, at least one incarnation of it :)).

**Comment by ge0ffrey** [comment]
Adjusted readme.adoc to add a link to it.

**Comment by mdanter** [comment]
Thank you, @ge0ffrey !
