### ISSUE TITLE
Introduce Tests

### ISSUE THREAD

**Issue by mdanter** [ge0ffrey/optaconf#8]
introduce a maven artifact that uses Arquillian for integration testing the app. Set this up so that it runs after the web app is built to grab the war from optaconf-webapp/target and use that to run the integration tests in Arquillian embedded mode with wildfly using apache httpclient.

**Comment by ge0ffrey** [comment]
I 've got a working arquillian test now and pushed it, but I am cleaning it up now.

**Comment by mdanter** [comment]
I saw that after I assigned this to myself. You're awesome!
